/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.grow.gamification.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.grow.gamification.model.BadgeGroup;
import com.liferay.grow.gamification.model.BadgeGroupModel;
import com.liferay.grow.gamification.model.BadgeGroupSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BadgeGroup service. Represents a row in the &quot;gamification_BadgeGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link BadgeGroupModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BadgeGroupImpl}.
 * </p>
 *
 * @author Vilmos Papp
 * @see BadgeGroupImpl
 * @see BadgeGroup
 * @see BadgeGroupModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class BadgeGroupModelImpl extends BaseModelImpl<BadgeGroup>
	implements BadgeGroupModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a badge group model instance should use the {@link BadgeGroup} interface instead.
	 */
	public static final String TABLE_NAME = "gamification_BadgeGroup";
	public static final Object[][] TABLE_COLUMNS = {
			{ "badgeGroupId", Types.BIGINT },
			{ "groupName", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("badgeGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table gamification_BadgeGroup (badgeGroupId LONG not null primary key,groupName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table gamification_BadgeGroup";
	public static final String ORDER_BY_JPQL = " ORDER BY badgeGroup.badgeGroupId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gamification_BadgeGroup.badgeGroupId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.grow.gamification.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.grow.gamification.model.BadgeGroup"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.grow.gamification.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.grow.gamification.model.BadgeGroup"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BadgeGroup toModel(BadgeGroupSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BadgeGroup model = new BadgeGroupImpl();

		model.setBadgeGroupId(soapModel.getBadgeGroupId());
		model.setGroupName(soapModel.getGroupName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BadgeGroup> toModels(BadgeGroupSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BadgeGroup> models = new ArrayList<BadgeGroup>(soapModels.length);

		for (BadgeGroupSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.grow.gamification.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.grow.gamification.model.BadgeGroup"));

	public BadgeGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _badgeGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBadgeGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _badgeGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BadgeGroup.class;
	}

	@Override
	public String getModelClassName() {
		return BadgeGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BadgeGroup, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BadgeGroup, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<BadgeGroup, Object> attributeGetterFunction = entry.getValue();

			attributes.put(attributeName,
				attributeGetterFunction.apply((BadgeGroup)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BadgeGroup, Object>> attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BadgeGroup, Object> attributeSetterBiConsumer = attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((BadgeGroup)this,
					entry.getValue());
			}
		}
	}

	public Map<String, Function<BadgeGroup, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BadgeGroup, Object>> getAttributeSetterBiConsumers() {
		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<BadgeGroup, Object>> _attributeGetterFunctions;
	private static final Map<String, BiConsumer<BadgeGroup, Object>> _attributeSetterBiConsumers;

	static {
		Map<String, Function<BadgeGroup, Object>> attributeGetterFunctions = new LinkedHashMap<String, Function<BadgeGroup, Object>>();
		Map<String, BiConsumer<BadgeGroup, ?>> attributeSetterBiConsumers = new LinkedHashMap<String, BiConsumer<BadgeGroup, ?>>();


		attributeGetterFunctions.put(
			"badgeGroupId",
			new Function<BadgeGroup, Object>() {

				@Override
				public Object apply(BadgeGroup badgeGroup) {
					return badgeGroup.getBadgeGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"badgeGroupId",
			new BiConsumer<BadgeGroup, Object>() {

				@Override
				public void accept(BadgeGroup badgeGroup, Object badgeGroupId) {
					badgeGroup.setBadgeGroupId((Long)badgeGroupId);
				}

			});
		attributeGetterFunctions.put(
			"groupName",
			new Function<BadgeGroup, Object>() {

				@Override
				public Object apply(BadgeGroup badgeGroup) {
					return badgeGroup.getGroupName();
				}

			});
		attributeSetterBiConsumers.put(
			"groupName",
			new BiConsumer<BadgeGroup, Object>() {

				@Override
				public void accept(BadgeGroup badgeGroup, Object groupName) {
					badgeGroup.setGroupName((String)groupName);
				}

			});


		_attributeGetterFunctions = Collections.unmodifiableMap(attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap((Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getBadgeGroupId() {
		return _badgeGroupId;
	}

	@Override
	public void setBadgeGroupId(long badgeGroupId) {
		_badgeGroupId = badgeGroupId;
	}

	@JSON
	@Override
	public String getGroupName() {
		if (_groupName == null) {
			return "";
		}
		else {
			return _groupName;
		}
	}

	@Override
	public void setGroupName(String groupName) {
		_groupName = groupName;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			BadgeGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BadgeGroup toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BadgeGroup)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BadgeGroupImpl badgeGroupImpl = new BadgeGroupImpl();

		badgeGroupImpl.setBadgeGroupId(getBadgeGroupId());
		badgeGroupImpl.setGroupName(getGroupName());

		badgeGroupImpl.resetOriginalValues();

		return badgeGroupImpl;
	}

	@Override
	public int compareTo(BadgeGroup badgeGroup) {
		long primaryKey = badgeGroup.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BadgeGroup)) {
			return false;
		}

		BadgeGroup badgeGroup = (BadgeGroup)obj;

		long primaryKey = badgeGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<BadgeGroup> toCacheModel() {
		BadgeGroupCacheModel badgeGroupCacheModel = new BadgeGroupCacheModel();

		badgeGroupCacheModel.badgeGroupId = getBadgeGroupId();

		badgeGroupCacheModel.groupName = getGroupName();

		String groupName = badgeGroupCacheModel.groupName;

		if ((groupName != null) && (groupName.length() == 0)) {
			badgeGroupCacheModel.groupName = null;
		}

		return badgeGroupCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BadgeGroup, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler((4 * attributeGetterFunctions.size()) +
				2);

		sb.append("{");

		for (Map.Entry<String, Function<BadgeGroup, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<BadgeGroup, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((BadgeGroup)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<BadgeGroup, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler((5 * attributeGetterFunctions.size()) +
				4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<BadgeGroup, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<BadgeGroup, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((BadgeGroup)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = BadgeGroup.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			BadgeGroup.class, ModelWrapper.class
		};
	private long _badgeGroupId;
	private String _groupName;
	private BadgeGroup _escapedModel;
}