/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.grow.gamification.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.grow.gamification.model.LDate;
import com.liferay.grow.gamification.model.LDateModel;
import com.liferay.grow.gamification.model.LDateSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LDate service. Represents a row in the &quot;gamification_LDate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LDateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LDateImpl}.
 * </p>
 *
 * @author Vilmos Papp
 * @see LDateImpl
 * @see LDate
 * @see LDateModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class LDateModelImpl extends BaseModelImpl<LDate> implements LDateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a l date model instance should use the {@link LDate} interface instead.
	 */
	public static final String TABLE_NAME = "gamification_LDate";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dateId", Types.BIGINT },
			{ "year", Types.INTEGER },
			{ "month", Types.INTEGER },
			{ "monthName", Types.VARCHAR },
			{ "day", Types.INTEGER },
			{ "dayOfYear", Types.INTEGER },
			{ "week", Types.INTEGER },
			{ "weekDay", Types.VARCHAR },
			{ "quarter", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("dateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("year", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("month", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("monthName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("day", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("dayOfYear", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("week", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("weekDay", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("quarter", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table gamification_LDate (dateId LONG not null primary key,year INTEGER,month INTEGER,monthName VARCHAR(75) null,day INTEGER,dayOfYear INTEGER,week INTEGER,weekDay VARCHAR(75) null,quarter VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table gamification_LDate";
	public static final String ORDER_BY_JPQL = " ORDER BY lDate.dateId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gamification_LDate.dateId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.grow.gamification.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.grow.gamification.model.LDate"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.grow.gamification.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.grow.gamification.model.LDate"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.grow.gamification.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.grow.gamification.model.LDate"),
			true);
	public static final long DAY_COLUMN_BITMASK = 1L;
	public static final long MONTH_COLUMN_BITMASK = 2L;
	public static final long YEAR_COLUMN_BITMASK = 4L;
	public static final long DATEID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LDate toModel(LDateSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LDate model = new LDateImpl();

		model.setDateId(soapModel.getDateId());
		model.setYear(soapModel.getYear());
		model.setMonth(soapModel.getMonth());
		model.setMonthName(soapModel.getMonthName());
		model.setDay(soapModel.getDay());
		model.setDayOfYear(soapModel.getDayOfYear());
		model.setWeek(soapModel.getWeek());
		model.setWeekDay(soapModel.getWeekDay());
		model.setQuarter(soapModel.getQuarter());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LDate> toModels(LDateSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LDate> models = new ArrayList<LDate>(soapModels.length);

		for (LDateSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.grow.gamification.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.grow.gamification.model.LDate"));

	public LDateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LDate.class;
	}

	@Override
	public String getModelClassName() {
		return LDate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LDate, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LDate, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<LDate, Object> attributeGetterFunction = entry.getValue();

			attributes.put(attributeName,
				attributeGetterFunction.apply((LDate)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LDate, Object>> attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LDate, Object> attributeSetterBiConsumer = attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((LDate)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LDate, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LDate, Object>> getAttributeSetterBiConsumers() {
		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<LDate, Object>> _attributeGetterFunctions;
	private static final Map<String, BiConsumer<LDate, Object>> _attributeSetterBiConsumers;

	static {
		Map<String, Function<LDate, Object>> attributeGetterFunctions = new LinkedHashMap<String, Function<LDate, Object>>();
		Map<String, BiConsumer<LDate, ?>> attributeSetterBiConsumers = new LinkedHashMap<String, BiConsumer<LDate, ?>>();


		attributeGetterFunctions.put(
			"dateId",
			new Function<LDate, Object>() {

				@Override
				public Object apply(LDate lDate) {
					return lDate.getDateId();
				}

			});
		attributeSetterBiConsumers.put(
			"dateId",
			new BiConsumer<LDate, Object>() {

				@Override
				public void accept(LDate lDate, Object dateId) {
					lDate.setDateId((Long)dateId);
				}

			});
		attributeGetterFunctions.put(
			"year",
			new Function<LDate, Object>() {

				@Override
				public Object apply(LDate lDate) {
					return lDate.getYear();
				}

			});
		attributeSetterBiConsumers.put(
			"year",
			new BiConsumer<LDate, Object>() {

				@Override
				public void accept(LDate lDate, Object year) {
					lDate.setYear((Integer)year);
				}

			});
		attributeGetterFunctions.put(
			"month",
			new Function<LDate, Object>() {

				@Override
				public Object apply(LDate lDate) {
					return lDate.getMonth();
				}

			});
		attributeSetterBiConsumers.put(
			"month",
			new BiConsumer<LDate, Object>() {

				@Override
				public void accept(LDate lDate, Object month) {
					lDate.setMonth((Integer)month);
				}

			});
		attributeGetterFunctions.put(
			"monthName",
			new Function<LDate, Object>() {

				@Override
				public Object apply(LDate lDate) {
					return lDate.getMonthName();
				}

			});
		attributeSetterBiConsumers.put(
			"monthName",
			new BiConsumer<LDate, Object>() {

				@Override
				public void accept(LDate lDate, Object monthName) {
					lDate.setMonthName((String)monthName);
				}

			});
		attributeGetterFunctions.put(
			"day",
			new Function<LDate, Object>() {

				@Override
				public Object apply(LDate lDate) {
					return lDate.getDay();
				}

			});
		attributeSetterBiConsumers.put(
			"day",
			new BiConsumer<LDate, Object>() {

				@Override
				public void accept(LDate lDate, Object day) {
					lDate.setDay((Integer)day);
				}

			});
		attributeGetterFunctions.put(
			"dayOfYear",
			new Function<LDate, Object>() {

				@Override
				public Object apply(LDate lDate) {
					return lDate.getDayOfYear();
				}

			});
		attributeSetterBiConsumers.put(
			"dayOfYear",
			new BiConsumer<LDate, Object>() {

				@Override
				public void accept(LDate lDate, Object dayOfYear) {
					lDate.setDayOfYear((Integer)dayOfYear);
				}

			});
		attributeGetterFunctions.put(
			"week",
			new Function<LDate, Object>() {

				@Override
				public Object apply(LDate lDate) {
					return lDate.getWeek();
				}

			});
		attributeSetterBiConsumers.put(
			"week",
			new BiConsumer<LDate, Object>() {

				@Override
				public void accept(LDate lDate, Object week) {
					lDate.setWeek((Integer)week);
				}

			});
		attributeGetterFunctions.put(
			"weekDay",
			new Function<LDate, Object>() {

				@Override
				public Object apply(LDate lDate) {
					return lDate.getWeekDay();
				}

			});
		attributeSetterBiConsumers.put(
			"weekDay",
			new BiConsumer<LDate, Object>() {

				@Override
				public void accept(LDate lDate, Object weekDay) {
					lDate.setWeekDay((String)weekDay);
				}

			});
		attributeGetterFunctions.put(
			"quarter",
			new Function<LDate, Object>() {

				@Override
				public Object apply(LDate lDate) {
					return lDate.getQuarter();
				}

			});
		attributeSetterBiConsumers.put(
			"quarter",
			new BiConsumer<LDate, Object>() {

				@Override
				public void accept(LDate lDate, Object quarter) {
					lDate.setQuarter((String)quarter);
				}

			});


		_attributeGetterFunctions = Collections.unmodifiableMap(attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap((Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getDateId() {
		return _dateId;
	}

	@Override
	public void setDateId(long dateId) {
		_dateId = dateId;
	}

	@JSON
	@Override
	public int getYear() {
		return _year;
	}

	@Override
	public void setYear(int year) {
		_columnBitmask |= YEAR_COLUMN_BITMASK;

		if (!_setOriginalYear) {
			_setOriginalYear = true;

			_originalYear = _year;
		}

		_year = year;
	}

	public int getOriginalYear() {
		return _originalYear;
	}

	@JSON
	@Override
	public int getMonth() {
		return _month;
	}

	@Override
	public void setMonth(int month) {
		_columnBitmask |= MONTH_COLUMN_BITMASK;

		if (!_setOriginalMonth) {
			_setOriginalMonth = true;

			_originalMonth = _month;
		}

		_month = month;
	}

	public int getOriginalMonth() {
		return _originalMonth;
	}

	@JSON
	@Override
	public String getMonthName() {
		if (_monthName == null) {
			return "";
		}
		else {
			return _monthName;
		}
	}

	@Override
	public void setMonthName(String monthName) {
		_monthName = monthName;
	}

	@JSON
	@Override
	public int getDay() {
		return _day;
	}

	@Override
	public void setDay(int day) {
		_columnBitmask |= DAY_COLUMN_BITMASK;

		if (!_setOriginalDay) {
			_setOriginalDay = true;

			_originalDay = _day;
		}

		_day = day;
	}

	public int getOriginalDay() {
		return _originalDay;
	}

	@JSON
	@Override
	public int getDayOfYear() {
		return _dayOfYear;
	}

	@Override
	public void setDayOfYear(int dayOfYear) {
		_dayOfYear = dayOfYear;
	}

	@JSON
	@Override
	public int getWeek() {
		return _week;
	}

	@Override
	public void setWeek(int week) {
		_week = week;
	}

	@JSON
	@Override
	public String getWeekDay() {
		if (_weekDay == null) {
			return "";
		}
		else {
			return _weekDay;
		}
	}

	@Override
	public void setWeekDay(String weekDay) {
		_weekDay = weekDay;
	}

	@JSON
	@Override
	public String getQuarter() {
		if (_quarter == null) {
			return "";
		}
		else {
			return _quarter;
		}
	}

	@Override
	public void setQuarter(String quarter) {
		_quarter = quarter;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LDate.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LDate toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LDate)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LDateImpl lDateImpl = new LDateImpl();

		lDateImpl.setDateId(getDateId());
		lDateImpl.setYear(getYear());
		lDateImpl.setMonth(getMonth());
		lDateImpl.setMonthName(getMonthName());
		lDateImpl.setDay(getDay());
		lDateImpl.setDayOfYear(getDayOfYear());
		lDateImpl.setWeek(getWeek());
		lDateImpl.setWeekDay(getWeekDay());
		lDateImpl.setQuarter(getQuarter());

		lDateImpl.resetOriginalValues();

		return lDateImpl;
	}

	@Override
	public int compareTo(LDate lDate) {
		long primaryKey = lDate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LDate)) {
			return false;
		}

		LDate lDate = (LDate)obj;

		long primaryKey = lDate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LDateModelImpl lDateModelImpl = this;

		lDateModelImpl._originalYear = lDateModelImpl._year;

		lDateModelImpl._setOriginalYear = false;

		lDateModelImpl._originalMonth = lDateModelImpl._month;

		lDateModelImpl._setOriginalMonth = false;

		lDateModelImpl._originalDay = lDateModelImpl._day;

		lDateModelImpl._setOriginalDay = false;

		lDateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LDate> toCacheModel() {
		LDateCacheModel lDateCacheModel = new LDateCacheModel();

		lDateCacheModel.dateId = getDateId();

		lDateCacheModel.year = getYear();

		lDateCacheModel.month = getMonth();

		lDateCacheModel.monthName = getMonthName();

		String monthName = lDateCacheModel.monthName;

		if ((monthName != null) && (monthName.length() == 0)) {
			lDateCacheModel.monthName = null;
		}

		lDateCacheModel.day = getDay();

		lDateCacheModel.dayOfYear = getDayOfYear();

		lDateCacheModel.week = getWeek();

		lDateCacheModel.weekDay = getWeekDay();

		String weekDay = lDateCacheModel.weekDay;

		if ((weekDay != null) && (weekDay.length() == 0)) {
			lDateCacheModel.weekDay = null;
		}

		lDateCacheModel.quarter = getQuarter();

		String quarter = lDateCacheModel.quarter;

		if ((quarter != null) && (quarter.length() == 0)) {
			lDateCacheModel.quarter = null;
		}

		return lDateCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LDate, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler((4 * attributeGetterFunctions.size()) +
				2);

		sb.append("{");

		for (Map.Entry<String, Function<LDate, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<LDate, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LDate)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LDate, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler((5 * attributeGetterFunctions.size()) +
				4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LDate, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<LDate, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LDate)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = LDate.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			LDate.class, ModelWrapper.class
		};
	private long _dateId;
	private int _year;
	private int _originalYear;
	private boolean _setOriginalYear;
	private int _month;
	private int _originalMonth;
	private boolean _setOriginalMonth;
	private String _monthName;
	private int _day;
	private int _originalDay;
	private boolean _setOriginalDay;
	private int _dayOfYear;
	private int _week;
	private String _weekDay;
	private String _quarter;
	private long _columnBitmask;
	private LDate _escapedModel;
}