/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.social.activity.customizer.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.social.activity.customizer.model.CustomSocialActivitySet;
import com.liferay.social.activity.customizer.model.CustomSocialActivitySetModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CustomSocialActivitySet service. Represents a row in the &quot;sac_CustomSocialActivitySet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CustomSocialActivitySetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomSocialActivitySetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomSocialActivitySetImpl
 * @generated
 */
public class CustomSocialActivitySetModelImpl
	extends BaseModelImpl<CustomSocialActivitySet>
	implements CustomSocialActivitySetModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a custom social activity set model instance should use the <code>CustomSocialActivitySet</code> interface instead.
	 */
	public static final String TABLE_NAME = "sac_CustomSocialActivitySet";

	public static final Object[][] TABLE_COLUMNS = {{"id_", Types.BIGINT}};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table sac_CustomSocialActivitySet (id_ LONG not null primary key)";

	public static final String TABLE_SQL_DROP =
		"drop table sac_CustomSocialActivitySet";

	public static final String ORDER_BY_JPQL =
		" ORDER BY customSocialActivitySet.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY sac_CustomSocialActivitySet.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.social.activity.customizer.com.liferay.grow.social.activity.
			customizer.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.social.activity.customizer.model.CustomSocialActivitySet"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.social.activity.customizer.com.liferay.grow.social.activity.
			customizer.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.social.activity.customizer.model.CustomSocialActivitySet"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.social.activity.customizer.com.liferay.grow.social.activity.
			customizer.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.social.activity.customizer.model.CustomSocialActivitySet"));

	public CustomSocialActivitySetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CustomSocialActivitySet.class;
	}

	@Override
	public String getModelClassName() {
		return CustomSocialActivitySet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CustomSocialActivitySet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CustomSocialActivitySet, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CustomSocialActivitySet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CustomSocialActivitySet)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CustomSocialActivitySet, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CustomSocialActivitySet, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CustomSocialActivitySet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CustomSocialActivitySet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CustomSocialActivitySet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CustomSocialActivitySet>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CustomSocialActivitySet.class.getClassLoader(),
			CustomSocialActivitySet.class, ModelWrapper.class);

		try {
			Constructor<CustomSocialActivitySet> constructor =
				(Constructor<CustomSocialActivitySet>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CustomSocialActivitySet, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<CustomSocialActivitySet, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<CustomSocialActivitySet, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CustomSocialActivitySet, Object>>();
		Map<String, BiConsumer<CustomSocialActivitySet, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<CustomSocialActivitySet, ?>>();

		attributeGetterFunctions.put("id", CustomSocialActivitySet::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<CustomSocialActivitySet, Long>)
				CustomSocialActivitySet::setId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CustomSocialActivitySet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CustomSocialActivitySet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CustomSocialActivitySet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CustomSocialActivitySetImpl customSocialActivitySetImpl =
			new CustomSocialActivitySetImpl();

		customSocialActivitySetImpl.setId(getId());

		customSocialActivitySetImpl.resetOriginalValues();

		return customSocialActivitySetImpl;
	}

	@Override
	public int compareTo(CustomSocialActivitySet customSocialActivitySet) {
		long primaryKey = customSocialActivitySet.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CustomSocialActivitySet)) {
			return false;
		}

		CustomSocialActivitySet customSocialActivitySet =
			(CustomSocialActivitySet)obj;

		long primaryKey = customSocialActivitySet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CustomSocialActivitySet> toCacheModel() {
		CustomSocialActivitySetCacheModel customSocialActivitySetCacheModel =
			new CustomSocialActivitySetCacheModel();

		customSocialActivitySetCacheModel.id = getId();

		return customSocialActivitySetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CustomSocialActivitySet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CustomSocialActivitySet, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CustomSocialActivitySet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((CustomSocialActivitySet)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CustomSocialActivitySet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CustomSocialActivitySet, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CustomSocialActivitySet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((CustomSocialActivitySet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CustomSocialActivitySet>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _id;
	private CustomSocialActivitySet _escapedModel;

}